### ISSUE TITLE
Обсалютно не рабочий

### ISSUE THREAD

**Issue by Geraldiy** [pacas/RW-Empire-Rework#9]
Не работает от слова совсем,отображается желтым в списке модов,а также не работает.Подскажите решение данной проблемы

**Comment by pacas** [comment]
Отображается желтым - неправильно установили. Открыть релизы и правильно перенести папку, скачанную оттуда.

**Comment by Geraldiy** [comment]
спасибо

**Comment by Geraldiy** [comment]
Но...даже после того,как я установил последнюю версию этого мода,перекидывая папку из архива в папку с модами,он всеравно отображается оранжевым цветом...

**Comment by pacas** [comment]
Скачивалось отсюда по этим ссылкам?

https://github.com/pacas/RW-Empire-Rework/releases
https://github.com/pacas/RW-Empire-Rework/releases/download/v0.12.2/HMC.Nobility.Expanded.zip

**Comment by Geraldiy** [comment]
https://github.com/pacas/RW-Empire-Rework/archive/refs/tags/v0.12.2.zip
Качал по этой ссылке,увы,но я не опытен по управлению в гитхабе,потому извиняюсь если делаю что-то не так

**Comment by pacas** [comment]
Это скачивание репозитория. Там внутри всё равно есть мод, но ссылки на скачивание выше даны даже на странице мода.

**Comment by Geraldiy** [comment]
Простите,но проблема всеравно не решилась.Даже скачав по ссылке на странице мода,и распаковав архив в папку mods,всеравно мод выделяется жёлтым

**Comment by pacas** [comment]
Скрин того что внутри папки mods (конкретно этот мод) и внутри папки самого мода

**Comment by Geraldiy** [comment]
![RW-Empire-Rework-0 12 2 08 07 2023 2_37_22](https://github.com/pacas/RW-Empire-Rework/assets/138920855/6494ad99-88bb-40e3-b580-66f83173d3db)

**Comment by pacas** [comment]
Распакуй папку мода саму (внутри у тебя здесь). По второй ссылке выше она сразу была бы.

**Comment by Geraldiy** [comment]
проблема решилась,спасибо!
